import {
  RSection,
  RContainer,
  WireHeading,
  WireText,
  WireNavbar,
  WireFooter,
  WireDivider,
} from "./Wire";

/**
 * ReviewInsightCompareV3.tsx: head to head comparison, written as an article.
 *
 * V2 was a scoreboard. Everything on it could be read straight off G2 and
 * Capterra, which is what Google's spam policy calls stitching content from
 * other pages without adding value.
 *
 * V3 reports something the review platforms cannot: we read the reviews
 * ourselves and graded them. Prose is generated from a data brief and every
 * figure and quote is checked back against it, so the writing cannot drift
 * from the numbers beside it. Where the data does not explain a gap, the copy
 * says so rather than inventing a reason.
 *
 * Deliberately absent:
 *   1. No Review or AggregateRating markup. The review snippet rules forbid
 *      marking up a rating aggregated from other websites.
 *   2. No pair picker on the indexed page. Published comparisons are a curated
 *      set chosen by search demand; any-pair browsing belongs in the noindex
 *      tool at the foot.
 *
 * Generated by render_compare.py. Edit the generator, not this file.
 */

const COPY = {
  "h1": "ClickUp or Asana: which project management tool does the review evidence back?",
  "standfirst": "Platform agreement separates the two most, revealing whether customers encounter consistent behavior or sharply different experiences depending on where they land.",
  "headings": {
    "pick": "Which company fits which buyer",
    "glance": "How the two compare across four parts",
    "difference": "Platform agreement and what it reveals about consistency",
    "reviewers": "What customers of each company keep crediting or hitting",
    "spread": "The false impression a single review site creates",
    "method": "What we read to produce this comparison",
    "tool": "Compare two other project management companies"
  },
  "verdict": "ClickUp earns stronger review evidence across all four parts, with platform agreement revealing the sharpest difference in how consistently each company behaves. Asana's platforms disagree by 3.0 stars, with Trustpilot capturing a concentrated group of detractors the other sites miss entirely. ClickUp's 0.6 point spread suggests more predictable behavior regardless of which platform a buyer checks.",
  "who_should_pick_which": [
    "ClickUp suits buyers who need evidence the tool behaves predictably across different customer segments, particularly where consolidating multiple tools matters and where automations can recover hours per week.",
    "Asana suits buyers willing to accept that one platform captures a sharply critical group the others do not, and who can verify in a trial that their use case aligns with the positive reviewers on G2 rather than the detractors on Trustpilot."
  ],
  "biggest_difference": "Platform agreement separates the two most. Asana's platforms disagree by 3.0 stars, with Trustpilot at 1.5 pulling against the others. ClickUp's platforms agree within 0.6 stars. The gap implies Asana's Trustpilot reviewers encounter something the other platform populations do not, or that Trustpilot reaches a group the other sites miss. Most Trustpilot reviewers for both companies did not state a company size, so we cannot confirm who they are, but the concentration of detractors on that platform for Asana points to a body of critical experience the other sites do not reflect.",
  "what_reviewers_say": "ClickUp reviewers credit consolidation and time saved. One Trustpilot reviewer wrote the tool succeeded in \"cutting the number of tools I keep open; before, context was scattered across a few apps and things quietly fell out of sync\", and another reported \"the automations have saved us hours per week on status updates\". Critical voices mention learning curve and feature overload, but detractors remain a minority. Asana reviewers on Trustpilot describe abrupt policy changes and lost work, with one writing \"After I spent most of a day two weeks ago working out a calendar for my master's dissertation, everything disappeared when my free trial ended\" and another reporting \"they suddenly drop a 2-user limit on us without warning\". Positive reviewers on G2 and Capterra describe clarity and structure, but detractors dominate Trustpilot.",
  "platform_disagreement": "A buyer checking only Capterra for Asana would see 4.5 stars and 45 percent of all reviews, concluding the tool performs well. Checking only Trustpilot would show 1.5 stars and a concentrated group of detractors describing lost work and policy changes without warning. Trustpilot misleads most for Asana, but in the opposite direction: it captures a critical population the other platforms do not reflect.",
  "before_you_buy": [
    "Test what happens to your work when a free trial ends or a plan changes, particularly if you are building anything you cannot afford to lose overnight.",
    "Confirm in writing what the user limit is and whether it can change without notice, especially if you are starting small and expect to add people later.",
    "Run a trial with the actual automations and integrations you need, and measure whether they recover the hours ClickUp reviewers report or introduce the sync issues Asana detractors describe."
  ],
  "method": "We read 274 reviews across both companies: 127 for ClickUp across Trustpilot, G2, and Capterra, and 147 for Asana across the same three platforms. 38 ClickUp reviewers and 37 Asana reviewers named a checkable outcome."
};

const DATA = {
  "A": {
    "name": "ClickUp",
    "rating": 87,
    "reviewsTotal": "19,713",
    "read": 127,
    "spread": 0.6,
    "spreadLow": {
      "name": "Trustpilot",
      "rating": 4
    },
    "spreadHigh": {
      "name": "G2",
      "rating": 4.6
    },
    "platforms": [
      {
        "name": "G2",
        "rating": 4.6,
        "reviews": "13,689"
      },
      {
        "name": "Capterra",
        "rating": 4.6,
        "reviews": "4,615"
      },
      {
        "name": "Gartner Peer Insights",
        "rating": 4.5,
        "reviews": "756"
      },
      {
        "name": "Trustpilot",
        "rating": 4,
        "reviews": "653"
      }
    ]
  },
  "B": {
    "name": "Asana",
    "rating": 62,
    "reviewsTotal": "30,237",
    "read": 147,
    "spread": 3.0,
    "spreadLow": {
      "name": "Trustpilot",
      "rating": 1.5
    },
    "spreadHigh": {
      "name": "Capterra",
      "rating": 4.5
    },
    "platforms": [
      {
        "name": "Capterra",
        "rating": 4.5,
        "reviews": "13,631"
      },
      {
        "name": "Gartner Peer Insights",
        "rating": 4.5,
        "reviews": "2,446"
      },
      {
        "name": "G2",
        "rating": 4.4,
        "reviews": "13,853"
      },
      {
        "name": "Trustpilot",
        "rating": 1.5,
        "reviews": "307"
      }
    ]
  },
  "parts": [
    {
      "label": "Review Avg",
      "a": 91.5,
      "b": 88.5,
      "gap": 3.0
    },
    {
      "label": "Reliable",
      "a": 81.6,
      "b": 7.0,
      "gap": 74.6
    },
    {
      "label": "Recent",
      "a": 97.7,
      "b": 86.7,
      "gap": 11.0
    },
    {
      "label": "Result-Specific",
      "a": 76.0,
      "b": 67.0,
      "gap": 9.0
    }
  ],
  "quotes": [
    {
      "company": "ClickUp",
      "positive": {
        "quote": "get insights into behaviors and opportunities to improve productivity",
        "platform": "Trustpilot",
        "date": "08 Aug 2026",
        "role": null,
        "company_size": null
      },
      "critical": {
        "quote": "costing my team valuable time on critical path projects",
        "platform": "Trustpilot",
        "date": "11 Aug 2026",
        "role": null,
        "company_size": null
      }
    },
    {
      "company": "Asana",
      "positive": {
        "quote": "It helped me bring structure and clarity to managing my beauty coworking space, especially with part-time staff",
        "platform": "Capterra",
        "date": "24 Mar 2026",
        "role": "Founder",
        "company_size": "2-10 employees"
      },
      "critical": {
        "quote": "After I spent most of a day two weeks ago working out a calendar for my master's dissertation, everything disappeared when my free trial ended",
        "platform": "Trustpilot",
        "date": "07 Jul 2026",
        "role": null,
        "company_size": null
      }
    }
  ],
  "category": "Project Management",
  "ratingGap": 25,
  "medianSpread": 2.4,
  "updated": "12 August 2026"
};

/* ---------- Header ---------- */

const HeaderSection = () => (
  <RSection size="md" bg="white" sectionName="header">
    <RContainer className="max-w-3xl">
      <p className="mb-3 text-xs font-semibold uppercase tracking-wider text-gray-400">
        {DATA.category} &middot; Head to head
      </p>
      <WireHeading level={1} copyId="reviewinsight.compare.title" className="mb-5">
        {COPY.h1}
      </WireHeading>
      <WireText copyId="reviewinsight.compare.standfirst" className="text-lg text-gray-700">
        {COPY.standfirst}
      </WireText>
      <div className="mt-6 flex flex-wrap items-center gap-x-5 gap-y-2 text-sm text-gray-500">
        <span>
          By the <span className="font-semibold text-gray-700">ReviewInsight desk</span>
        </span>
        <span className="text-gray-300">|</span>
        <span>Last updated {DATA.updated}</span>
        <span className="text-gray-300">|</span>
        <span className="underline">How we rate</span>
      </div>
    </RContainer>
  </RSection>
);

/* ---------- Verdict ---------- */

const VerdictSection = () => (
  <RSection size="sm" bg="white" sectionName="verdict">
    <RContainer className="max-w-3xl">
      <div className="border-l-2 border-gray-900 pl-6">
        <WireText copyId="reviewinsight.compare.verdict" className="text-gray-700">
          {COPY.verdict}
        </WireText>
      </div>
    </RContainer>
  </RSection>
);

/* ---------- Who should pick which ---------- */

const PickSection = () => (
  <RSection bg="light" sectionName="who-should-pick">
    <RContainer className="max-w-4xl">
      <WireHeading level={2} copyId="reviewinsight.compare.pick.heading" className="mb-6">
        {COPY.headings.pick}
      </WireHeading>
      <div className="grid gap-px bg-gray-200 md:grid-cols-2">
        {[DATA.A, DATA.B].map((c, i) => (
          <div key={c.name} className="bg-white p-6">
            <div className="mb-3 flex items-center gap-3">
              <div className="flex size-12 shrink-0 items-center justify-center border-2 border-gray-900">
                <span className="font-bold text-gray-900">{c.rating}</span>
              </div>
              <p className="font-semibold text-gray-900">{c.name}</p>
            </div>
            <WireText
              copyId={`reviewinsight.compare.pick.${i}`}
              className="text-sm text-gray-600"
            >
              {COPY.who_should_pick_which[i]}
            </WireText>
          </div>
        ))}
      </div>
    </RContainer>
  </RSection>
);

/* ---------- At a glance ---------- */

const GlanceSection = () => (
  <RSection bg="white" sectionName="at-a-glance">
    <RContainer className="max-w-4xl">
      <WireHeading level={2} copyId="reviewinsight.compare.glance.heading" className="mb-6">
        {COPY.headings.glance}
      </WireHeading>
      <div className="overflow-x-auto border border-gray-200 bg-white">
        <table className="w-full text-left text-sm">
          <thead>
            <tr className="border-b-2 border-gray-900">
              <th className="px-5 py-3 font-semibold text-gray-900">Part</th>
              <th className="px-5 py-3 text-right font-semibold text-gray-900">{DATA.A.name}</th>
              <th className="px-5 py-3 text-right font-semibold text-gray-900">{DATA.B.name}</th>
              <th className="px-5 py-3 text-right font-semibold text-gray-900">Gap</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b border-gray-200 bg-gray-50">
              <td className="px-5 py-3 font-semibold text-gray-900">ReviewInsight Rating</td>
              <td className="px-5 py-3 text-right font-bold text-gray-900">{DATA.A.rating}</td>
              <td className="px-5 py-3 text-right font-bold text-gray-900">{DATA.B.rating}</td>
              <td className="px-5 py-3 text-right font-semibold text-gray-700">{DATA.ratingGap}</td>
            </tr>
            {DATA.parts.map((p) => (
              <tr key={p.label} className="border-b border-gray-200">
                <td className="px-5 py-3 text-gray-700">{p.label}</td>
                <td className="px-5 py-3 text-right text-gray-900">{p.a}</td>
                <td className="px-5 py-3 text-right text-gray-900">{p.b}</td>
                <td className="px-5 py-3 text-right text-gray-500">{p.gap}</td>
              </tr>
            ))}
            <tr className="border-b border-gray-200">
              <td className="px-5 py-3 text-gray-700">Reviews behind the average</td>
              <td className="px-5 py-3 text-right text-gray-900">{DATA.A.reviewsTotal}</td>
              <td className="px-5 py-3 text-right text-gray-900">{DATA.B.reviewsTotal}</td>
              <td className="px-5 py-3 text-right text-gray-500">&nbsp;</td>
            </tr>
            <tr>
              <td className="px-5 py-3 text-gray-700">Reviews we read closely</td>
              <td className="px-5 py-3 text-right text-gray-900">{DATA.A.read}</td>
              <td className="px-5 py-3 text-right text-gray-900">{DATA.B.read}</td>
              <td className="px-5 py-3 text-right text-gray-500">&nbsp;</td>
            </tr>
          </tbody>
        </table>
      </div>
    </RContainer>
  </RSection>
);

/* ---------- Biggest difference ---------- */

const DifferenceSection = () => (
  <RSection bg="light" sectionName="biggest-difference">
    <RContainer className="max-w-4xl">
      <WireHeading level={2} copyId="reviewinsight.compare.difference.heading" className="mb-4">
        {COPY.headings.difference}
      </WireHeading>
      <WireText
        copyId="reviewinsight.compare.difference.body"
        className="mb-8 max-w-2xl text-gray-700"
      >
        {COPY.biggest_difference}
      </WireText>
      <div className="grid gap-px bg-gray-200 md:grid-cols-2">
        {[DATA.A, DATA.B].map((c) => (
          <div key={c.name} className="bg-white p-6">
            <p className="mb-1 font-semibold text-gray-900">{c.name}</p>
            <p className="mb-4 text-sm text-gray-500">
              {c.spread} point spread, {c.spreadLow.name} {c.spreadLow.rating} to{" "}
              {c.spreadHigh.name} {c.spreadHigh.rating}
            </p>
            <div className="flex flex-col gap-2">
              {c.platforms.map((p) => (
                <div key={p.name} className="flex items-center gap-3">
                  <span className="w-44 shrink-0 text-sm text-gray-600">{p.name}</span>
                  <div className="h-2 flex-1 bg-gray-100">
                    <div className="h-2 bg-gray-900" style={{ width: `${(p.rating / 5) * 100}%` }} />
                  </div>
                  <span className="w-8 shrink-0 text-right text-sm font-semibold text-gray-900">
                    {p.rating}
                  </span>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
    </RContainer>
  </RSection>
);

/* ---------- What reviewers say ---------- */

const ReviewersSection = () => (
  <RSection bg="white" sectionName="what-reviewers-say">
    <RContainer className="max-w-4xl">
      <WireHeading level={2} copyId="reviewinsight.compare.reviewers.heading" className="mb-4">
        {COPY.headings.reviewers}
      </WireHeading>
      <WireText
        copyId="reviewinsight.compare.reviewers.body"
        className="mb-8 max-w-2xl text-gray-700"
      >
        {COPY.what_reviewers_say}
      </WireText>
      <div className="grid gap-px bg-gray-200 md:grid-cols-2">
        {DATA.quotes.map((q) => (
          <div key={q.company} className="bg-white p-6">
            <p className="mb-4 font-semibold text-gray-900">{q.company}</p>
            {q.positive && (
              <div className="mb-5">
                <blockquote className="border-l-2 border-gray-900 pl-4 text-sm italic text-gray-700">
                  {q.positive.quote}
                </blockquote>
                <p className="mt-2 text-xs text-gray-400">
                  {q.positive.platform}
                  {q.positive.date ? `, ${q.positive.date}` : ""}
                </p>
              </div>
            )}
            {q.critical && (
              <div>
                <blockquote className="border-l-2 border-gray-300 pl-4 text-sm italic text-gray-500">
                  {q.critical.quote}
                </blockquote>
                <p className="mt-2 text-xs text-gray-400">
                  {q.critical.platform}
                  {q.critical.date ? `, ${q.critical.date}` : ""}
                </p>
              </div>
            )}
          </div>
        ))}
      </div>
    </RContainer>
  </RSection>
);

/* ---------- Platform disagreement ---------- */

const DisagreementSection = () => (
  <RSection bg="light" sectionName="platform-disagreement">
    <RContainer className="max-w-4xl">
      <WireHeading level={2} copyId="reviewinsight.compare.spread.heading" className="mb-4">
        {COPY.headings.spread}
      </WireHeading>
      <WireText copyId="reviewinsight.compare.spread.body" className="max-w-2xl text-gray-700">
        {COPY.platform_disagreement}
      </WireText>
    </RContainer>
  </RSection>
);

/* ---------- Before you buy ---------- */

const BeforeYouBuySection = () => (
  <RSection bg="white" sectionName="before-you-buy">
    <RContainer className="max-w-4xl">
      <WireHeading level={2} copyId="reviewinsight.compare.before.heading" className="mb-6">
        Before you buy either
      </WireHeading>
      <div className="flex flex-col gap-px bg-gray-200">
        {COPY.before_you_buy.map((item, i) => (
          <div key={i} className="flex gap-4 bg-white p-6">
            <span className="text-sm font-semibold text-gray-400">{i + 1}</span>
            <WireText
              copyId={`reviewinsight.compare.before.${i}`}
              className="text-gray-700"
            >
              {item}
            </WireText>
          </div>
        ))}
      </div>
    </RContainer>
  </RSection>
);

/* ---------- Method ---------- */

const MethodSection = () => (
  <RSection bg="light" sectionName="method">
    <RContainer className="max-w-4xl">
      <WireHeading level={2} copyId="reviewinsight.compare.method.heading" className="mb-4">
        {COPY.headings.method}
      </WireHeading>
      <WireText copyId="reviewinsight.compare.method.body" className="mb-6 max-w-2xl text-gray-700">
        {COPY.method}
      </WireText>
      <div className="border border-gray-200 bg-white p-6">
        <p className="mb-2 text-sm font-semibold text-gray-900">
          No company can pay to be listed here or to change its rating.
        </p>
        <WireText copyId="reviewinsight.compare.method.note" className="text-sm text-gray-600">
          A higher rating means the review evidence behind a company is stronger, not that
          the product is better. We have not used either product. Every figure on this page
          can be rebuilt by hand from the method.
        </WireText>
        <p className="mt-4 text-sm font-semibold text-gray-900 underline">Read the full method</p>
      </div>
    </RContainer>
  </RSection>
);

/* ---------- Compare another pair ---------- */

const ToolSection = () => (
  <RSection bg="white" sectionName="compare-tool">
    <RContainer className="max-w-4xl">
      <div className="border border-dashed border-gray-400 bg-white p-8">
        <WireHeading level={2} copyId="reviewinsight.compare.tool.heading" className="mb-3">
          {COPY.headings.tool}
        </WireHeading>
        <WireText copyId="reviewinsight.compare.tool.body" className="mb-6 max-w-xl text-gray-600">
          Written comparisons cover the pairings buyers ask about most. To put any two rated
          companies side by side, use the comparison tool.
        </WireText>
        <div className="flex max-w-xl flex-col gap-2 sm:flex-row">
          <div className="flex-1 border border-gray-300 bg-white px-4 py-3 text-sm text-gray-400">
            First company
          </div>
          <div className="flex items-center justify-center px-2 text-sm text-gray-400">vs</div>
          <div className="flex-1 border border-gray-300 bg-white px-4 py-3 text-sm text-gray-400">
            Second company
          </div>
          <button className="border-2 border-gray-900 bg-gray-900 px-6 py-3 text-sm font-semibold text-white">
            Compare
          </button>
        </div>
        <p className="mt-4 text-xs text-gray-400" data-dev-note="true">
          Build note: the tool view is noindex. Only written comparisons like this page are
          indexable, so the site never ships thousands of near-identical generated pairings.
        </p>
      </div>
    </RContainer>
  </RSection>
);

/* ---------- Page ---------- */

export default function ReviewInsightCompareV3() {
  return (
    <>
      <WireNavbar
        logoSpec={{ kind: "wordmark", text: "ReviewInsight" }}
        links={["Categories", "Vendors", "Methodology", "Quarterly index"]}
        cta={false}
      />
      <HeaderSection />
      <VerdictSection />
      <PickSection />
      <GlanceSection />
      <DifferenceSection />
      <ReviewersSection />
      <DisagreementSection />
      <BeforeYouBuySection />
      <MethodSection />
      <ToolSection />
      <WireDivider />
      <WireFooter />
    </>
  );
}
